# dual_fuel_thermostat.toml: Example configuration file for a smart thermostat
# device controlled by Home Assistant MQTT switches that do not have a 1-to-1
# mapping to GPIO pins. Instead, the GPIO pins are controlled by custom logic
# in Python source code.
# 
# Consider a heating system fitted with both electrical and natural gas heating
# sources. By user preference, each heating source is modeled with its own Home
# Assistant Climate integration instance:
# 
# - A “Gas Heating” climate integration instance.
# - An “Electric Heating” climate integration instance.
# 
# Accordingly, the smart thermostat device exposes two Home Assistant MQTT
# switches, one for each climate integration. However, at the hardware level,
# the controls may be different:
# 
# - A “heat demand” GPIO pin: on = turn heating on, off = turn heating off.
# - A “fuel select” GPIO pin: on = electricity, off = natural gas.
# 
# The hardware thus prevents both heating sources from being active at the
# same time.
# 
# The source code in ‘products/dual_fuel_thermostat/dual_fuel_switches.py’
# implements the following logic to map the state of the Home Assistant
# MQTT switches to the state of the GPIO pins:
# 
#    |  Home Assistant Switches ||            GPIO pins            |
#    |--------------------------||---------------------------------|
#    | Gas Switch | Electrical  || ‘Heat Demand’  | ‘Fuel Select’  |
#    |   (Input)  | Switch (In) || GPIO pin (Out) | GPIO pin (Out) |
#    |------------|-------------||----------------|----------------|
#    |      0     |      0      ||        0       |       0        |
#    |      0     |      1      ||        1       |       1        |
#    |      1     |      0      ||        1       |       0        |
#    |      1     |      1      ||        1       |       1        |

# A product refers to a smart device category such as a smart power plug/socket
# or a smart thermostat. All products share a common core codebase, but each
# product may have some custom source code in a source code subdirectory.
[product]
# slug: A short name such as ‘smart_thermostat’ or ‘smart_socket’.
# This value is used in MQTT identifiers and in Docker container names.
slug = 'dual_fuel_thermostat'
# source_dir: Subdirectory of oh_so_smart/products/ that contains
# product-specific source code.
source_dir = 'dual_fuel_thermostat'

# The deployment section contains attributes of the hardware and software
# environment that the product will be deployed to. This section is used
# by deployment shell scripts rather than the application source code.
[deployment]
# docker_platforms: List of Docker platform identifiers for the target
# device (the device that runs the Oh So Smart app, e.g. a Raspberry Pi).
# A multi-platform Docker image is built if the list contains more than one
# platform. This setting is used by the ‘docker.py build’ script. Examples:
# - 'arm/v6'  (Raspberry Pi 1 and the original Pi Zero)
# - 'arm/v7'  (Raspberry Pi 2)
# - 'arm64'   (Raspberry Pi 3/4/5, Pi Zero 2)
# - 'i386' or '386'  (32-bit x86)
# - 'amd64' or 'x86_64' or 'x86-64'  (64-bit x86)
docker_platform = ['arm64']

# python_distro: The Python Docker image variant, either ‘alpine’ or ‘debian’.
# ‘distro’ is short for Linux Distribution. Choosing ‘alpine’ results in smaller
# Docker images, but it is not well supported on arm/v6 or arm/v7 (the PyPI
# `pydantic-core` package does not provide pre-built Python wheels for arm/v6
# and arm/v7). See also comments in the ‘Dockerfile.alpine’ file.
python_distro = 'alpine'

# ssh_host_name: The name of the ‘Host’ entry in your workstation’s
# ‘~/.ssh/config’ file (even on Microsoft Windows!) that configures ssh
# access for the target device. The target device is the device that runs
# the Oh So Smart app, e.g. a Raspberry Pi. This setting is used by the
# ‘docker.py’ and ‘upload.py’ deployment scripts. For example, ssh_host_name
# would be ‘pi4’ given the the following excerpt from ‘~/.ssh/config’:
#   Host pi4
#     Hostname 192.168.1.123
#     User root
#     Port 22
#     PreferredAuthentications publickey
#     ConnectTimeout 5
ssh_host_name = 'pi4'

# Project directory in the target device’s host operating system where the
# Oh So Smart application files are deployed. Check the README file and the
# help output of the ‘upload.py’ and ‘docker.py’ (or ‘docker.sh’) scripts for
# additional documentation.
host_os_project_dir = '/root/oh_so_smart'

# MQTT broker details.
[mqtt]
client_id = 'dual_fuel_thermostat'

# The MQTT server hostname, port number, username and password may be set here
# in the TOML configuration file. Alternatively, environment variables with the
# following names can be used:
#     MQTT_SERVER_HOSTNAME
#     MQTT_SERVER_PORT
#     MQTT_SERVER_USERNAME
#     MQTT_SERVER_PASSWORD
# These variables take precedence over the respective settings below. If the
# variables are set, the respective configuration lines below may be deleted.
[mqtt.server]
hostname = 'hostname_or_ip_address'
port = 1883
username = 'sample username'
password = 'sample password'

# Note: Double brackets [[...]] are TOML notation for an “array of tables”
# (a.k.a. “list of objects” or “list of dictionaries”).

# A sensor group (such as a group of DS18B20 temperature sensors) defines
# common attributes such as the MQTT topic. The ‘.sensors’ subsection lists
# each individual sensor in the group.
[[temperature_sensor_groups]]
mqtt_topic = 'dual_fuel_thermostat'
poll_interval_sec = 30
tolerate_missing_sensors = true
w1_gpio_pin = 7 # 1-wire protocol for DS18B20 thermometers

[[temperature_sensor_groups.sensors]]
# root@pi3:~# ls /sys/bus/w1/devices/
# 28-0722526be734  28-3ce1e3811e52  w1_bus_master1
mqtt_name = 'Hot water temperature'
type = 'ds18b20'
bus_id = '3ce1e3811e52'
offset = 0 # Positive or negative value added to the measurements
outlier_delta = 5  # Degree Celsius delta that defines an outlier measurement
outlier_window_size = 3  # Max number of measurements in the outlier filter window
noise_window_size = 5  # Max number of measurements in the noise filter window

# A switch group (such as a group of Home Assistant switches) defines common
# attributes such as the MQTT topic. The ‘.switches’ subsection lists each
# individual switch in the group.
[[switch_groups]]
mqtt_topic = 'dual_fuel_thermostat'
keep_alive_timeout_sec = 30  # HASS MQTT msg timeout period. 0 to disable.

# GPIO pin numbers are board header numbers. See ‘rpi_pin_map.py’.
[[switch_groups.switches]]
mqtt_name = 'Electric Hot Water'
slug = 'ehw_hass'  # Immutable ID that may be hardcoded in source code
gpio_pin = 13 # HW (Hot Water) HASS programmer

[[switch_groups.switches]]
mqtt_name = 'Gas Hot Water'
slug = 'ghw_hass'  # Immutable ID that may be hardcoded in source code
gpio_pin = 13 # HW (Hot Water) HASS programmer

# Details of any other GPIO pins (if any - optional) besides the pins used by
# sensors and switches listed above.
[[gpio]]
slug = 'hw_select'  # Immutable ID that may be hardcoded in source code
pin = 33 # HW (Hot Water) fuel select = off=gas, on=electric
direction = 'output'
